#!/bin/bash
# ==========================================
# MadOS ROG V2.5 - 17_bouclier_antipub.sh
# ==========================================
# Phase: 17 - Bouclier Anti-Pub / Malwares (Hosts)
# ==========================================

set -euo pipefail

RED='\033[0;31m'
WHITE='\033[1;37m'
GRAY='\033[0;90m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
NC='\033[0m'

echo -e "${RED}>>> ${WHITE}[Phase 17] ${BOLD}Déploiement du Bouclier Anti-Pub Global (Fichier Hosts)...${NC}"

HOSTS_URL="https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts"
HOSTS_TARGET="/etc/hosts"

echo -e "    ${GRAY}├─ Téléchargement de la base de données de StevenBlack...${NC}"

TEMP_HOSTS=$(mktemp)
if curl -sSL "$HOSTS_URL" -o "$TEMP_HOSTS"; then
    echo -e "    ${GRAY}├─ Injection dans le fichier host système...${NC}"
    
    # Nettoyer l'ancien hosts s'il avait déjà été modifié par ce script pour éviter les doublons géants
    sudo sed -i '/# === MADOS ROG AUTOGENERATED HOSTS ===/,/# === END MADOS ROG AUTOGENERATED HOSTS ===/d' "$HOSTS_TARGET"

    # Ajouter l'en-tête et les données
    cat <<'EOF' | sudo tee -a "$HOSTS_TARGET" >/dev/null

# === MADOS ROG AUTOGENERATED HOSTS ===
# Source: StevenBlack Unified Hosts (Ads & Malware Blocker)
EOF
    # Enlever les lignes "localhost" du fichier StevenBlack pour ne pas confliter avec l'existant système
    grep "^0\.0\.0\.0" "$TEMP_HOSTS" | sudo tee -a "$HOSTS_TARGET" >/dev/null
    
    echo "# === END MADOS ROG AUTOGENERATED HOSTS ===" | sudo tee -a "$HOSTS_TARGET" >/dev/null

    echo -e "    ${CYAN}✅ Plus de 100 000 serveurs publicitaires et malicieux bloqués au niveau du noyau réseau.${NC}"
else
    echo -e "    ${YELLOW}⚠️ Échec du téléchargement. Le bouclier n'a pas été appliqué.${NC}"
fi

rm -f "$TEMP_HOSTS"

echo -e "    ${WHITE}✅ Phase 17 Terminée.${NC}"
